- name: Configure T-Pot
  hosts: tpot
  become: true
  vars:
    ansible_port: 64295
    tpot_path: "{{ lookup('env', 'DEPLOY_PATH') }}"

  tasks:
    - name: Wait for SSH on new port
      wait_for_connection:
        timeout: 600

    - name: Stop T-Pot
      systemd:
        name: tpot
        state: stopped

    - name: Copy .env
      copy:
        src: /files/.env
        dest: "{{ tpot_path }}/.env"
        mode: "0600"

    - name: Copy docker-compose.yml
      copy:
        src: /files/docker-compose.yml
        dest: "{{ tpot_path }}/docker-compose.yml"
        mode: "0644"

    - name: Start T-Pot
      systemd:
        name: tpot
        state: started
        enabled: true
