- name: Configure T-Pot
  hosts: tpot
  become: true
  vars:
    ansible_port: 64295
    tpot_path: "{{ lookup('env', 'DEPLOY_PATH') }}"

  tasks:
    - name: Wait for SSH on new port
      wait_for_connection:
        timeout: 600

    - name: Copy .env
      copy:
        src: /files/.env
        dest: "{{ tpot_path }}/.env"
        mode: "0600"
        backup: true

    - name: Copy docker-compose.yml
      copy:
        src: /files/docker-compose.yml
        dest: "{{ tpot_path }}/docker-compose.yml"
        mode: "0644"
        backup: true

    - name: Copy forwarder folder
      copy:
        src: /files/forwarder/
        dest: "{{ tpot_path }}/docker/forwarder/"
        mode: "0644"
        backup: true
    - name: Set TPOT_NAME in forwarder .env
      lineinfile:
        path: "{{ tpot_path }}/docker/forwarder/.env"
        regexp: '^TPOT_NAME='
        line: "TPOT_NAME=tpot-{{ tpot_site }}"
        insertafter: '^VERIFY_TLS='

    - name: Set TPOT_SITE in forwarder .env
      lineinfile:
        path: "{{ tpot_path }}/docker/forwarder/.env"
        regexp: '^TPOT_SITE='
        line: "TPOT_SITE={{ tpot_site }}"
        insertafter: '^TPOT_NAME='

    - name: Stop T-Pot stack
      become_user: deployer
      command: docker compose down
      args:
        chdir: "{{ tpot_path }}"

    - name: Start T-Pot stack
      become_user: deployer
      command: docker compose up -d
      args:
        chdir: "{{ tpot_path }}"

    - name: Wait for Docker containers to settle
      pause:
        seconds: 20

    - name: Get running containers
      command: docker ps --format '{{ "{{.Names}}" }}'
      register: docker_ps
      changed_when: false

    - name: Check cowrie is running
      assert:
        that:
          - "'cowrie' in docker_ps.stdout_lines"
        fail_msg: "Cowrie n'est pas démarré."
        success_msg: "Cowrie est bien démarré."

    - name: Create forwarder state directory
      file:
        path: "{{ tpot_path }}/docker/forwarder/state"
        state: directory
        owner: deployer
        group: deployer
        mode: "0755"

    - name: Build and start forwarder
      become_user: deployer
      command: docker compose up -d --build
      args:
        chdir: "{{ tpot_path }}/docker/forwarder"
